/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author s1601396
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        SexPanel = new javax.swing.JPanel();
        CurrencyvariableZZZzzzZZZ = new javax.swing.JTextField();
        selectionbox69 = new javax.swing.JComboBox<>();
        xXxnotaselectionbox69xXx = new javax.swing.JTextField();
        BigSexy = new javax.swing.JPanel();
        result = new javax.swing.JTextField();
        ButtonXOXO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HornyPinkCalculator");
        setBackground(new java.awt.Color(255, 153, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SexPanel.setBackground(new java.awt.Color(255, 51, 255));
        SexPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.pink, java.awt.Color.pink, java.awt.Color.red, java.awt.Color.red));
        SexPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CurrencyvariableZZZzzzZZZ.setBackground(new java.awt.Color(255, 153, 255));
        SexPanel.add(CurrencyvariableZZZzzzZZZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 25));

        selectionbox69.setBackground(new java.awt.Color(255, 153, 255));
        selectionbox69.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Australian dollari  AUD  1,5008", "Bulgarian uusi lev  BGN  1,9558", "Brasilian real  BRL  3,7568", "Kanadan dollari  CAD  1,4866", "Sveitsin frangi  CHF  1,1389", "Kiinan juan renminbi  CNY  7,8979", "Tšekin koruna  CZK  26,102", "Tanskan kruunu  DKK  7,4393", "Englannin punta  GBP  0,9233", "Hongkongin dollari  HKD  9,3292", "Kroatian kuna  HRK  7,4145", "Unkarin forintti  HUF  304,01", "Indonesian rupia  IDR  15903,18", "Israelin uusi sekeli  ILS  4,2719", "Intian rupia  INR  76,2065", "Japanin jeni  JPY  130,34", "Etelä-Korean won  KRW  1335,56", "Meksikon peso  MXN  21,0584", "Malesian ringgit  MYR  5,0889", "Norjan kruunu  NOK  9,262", "Uuden-Seelannin dollari  NZD  1,6458", "Filippiinien peso  PHP  60,841", "Puolan zloty  PLN  4,2581", "Romanian uusi leu  RON  4,5977", "Venäjän rupla  RUB  69,659", "Ruotsin kruunu  SEK  9,5155", "Singaporen dollari  SGD  1,6156", "Thaimaan baht  THB  39,591", "Turkin liira  TRY  4,1063", "Taiwanin uusi dollari  TWD  35,8835", "Yhdysvaltain dollari  USD  1,1925", "Etelä-Afrikan randi  ZAR  15,5562" }));
        SexPanel.add(selectionbox69, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 320, 25));

        xXxnotaselectionbox69xXx.setEditable(false);
        xXxnotaselectionbox69xXx.setBackground(new java.awt.Color(255, 153, 255));
        xXxnotaselectionbox69xXx.setText("EUR");
        xXxnotaselectionbox69xXx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xXxnotaselectionbox69xXxActionPerformed(evt);
            }
        });
        SexPanel.add(xXxnotaselectionbox69xXx, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 320, 25));

        jPanel3.add(SexPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 480, 170));

        BigSexy.setBackground(new java.awt.Color(255, 0, 255));
        BigSexy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        result.setEditable(false);
        result.setBackground(new java.awt.Color(255, 153, 255));
        result.setFont(new java.awt.Font("Dialog", 0, 60)); // NOI18N
        result.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });
        BigSexy.add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 280, 110));

        ButtonXOXO.setBackground(new java.awt.Color(255, 153, 255));
        ButtonXOXO.setFont(new java.awt.Font("Dialog", 0, 40)); // NOI18N
        ButtonXOXO.setForeground(new java.awt.Color(255, 255, 255));
        ButtonXOXO.setText("Calculate");
        BigSexy.add(ButtonXOXO, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 200, 120));

        jPanel3.add(BigSexy, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 480, 120));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 530, 330));

        setSize(new java.awt.Dimension(516, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultActionPerformed

    private void xXxnotaselectionbox69xXxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xXxnotaselectionbox69xXxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xXxnotaselectionbox69xXxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BigSexy;
    private javax.swing.JButton ButtonXOXO;
    private javax.swing.JTextField CurrencyvariableZZZzzzZZZ;
    private javax.swing.JPanel SexPanel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField result;
    private javax.swing.JComboBox<String> selectionbox69;
    private javax.swing.JTextField xXxnotaselectionbox69xXx;
    // End of variables declaration//GEN-END:variables
}
